name: Coverage autotest

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.6'
    - name: Install pytest and coverage
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest coverage
    - name: Run pytest
      run: |
        python -m pytest ${{ github.head_ref }}/test_map.py
    - name: Run coverage
      run: |
        coverage run -m pytest ${{ github.head_ref }}/test_map.py && coverage report -m ${{ github.head_ref }}/test_map.py
